### ISSUE TITLE
Set priority of mutation types in genes 

### ISSUE THREAD

**Issue by wir963** [lrgr/explosig#87]
Each mutation type should be associated with a number, which indicates its priority or seriousness. ExploSig should always show the top priority mutation for a given sample. We should also use this priority when we sort by mutation type (screenshot https://cl.ly/0309d52f8964). This should resolve part 1 of issue #86. 

I propose we use the following priority (in rough order of impact)
Frameshift > Nonsense > Nonstop > in-frame indel > Missense > Splice Site > Translation Start Site > Other mutation > Silent > None

**Comment by keller-mark** [comment]
Done in https://github.com/lrgr/explosig-server/commit/9aee80331f291e0577194c4255b73a5b126dbd5d#diff-264f618d47c09314e7e4d290f7a64ab6
